# Generated by Django 5.2.11 on 2026-02-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_product_id_alter_variation_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variation",
            unique_together={("product", "variation_category", "variation_value")},
        ),
    ]
