# Generated by Django 6.0.1 on 2026-01-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
